### ISSUE TITLE
How to use it in node?

### ISSUE THREAD

**Issue by thearabbit** [joseshiru/p-loading#2] opened 2016-07-02 09:43 UTC
I use `Meteor`, I tried to install `p-loading

``` js
npm install p-loading --save

// usage
import ploading from '-loading';
.......
indexTmpl.events({
    'click .js-showLoading' (event, instance) {
        $("#spinner").ploading({action: 'show'});

```

But don't work, pl help me

**Comment by joseshiru** [comment] 2016-07-03 00:20
Hi,

Please update your node packages with `npm update`. And please use 
`import  'p-loading'`
instead of 
`import '-loading'`

In any case, the properties "main" and "styles" were missing in the package.json. So, now it should be working. ( I tested it).

In case the CSS files are not loaded, try to call them directly in the head of your HTML or
follow the instructions of this tutorial for add them with Meteor: https://guide.meteor.com/using-npm-packages.html 

Cheers,

Jose.

**Comment by thearabbit** [comment] 2016-07-03 02:46
I tried but don't work.

``` js
// html
<template name="hellpo">
  <div id="loading"></div>
</template>

// JS
import  ploading from 'p-loading';
import 'p-loading/dist/css/p-loading.css';
------
Template.hello.events({
    'click .js-showLoading' (event, instance) {
        $("#loading").ploading({action: 'show'});
```

**Comment by joseshiru** [comment] 2016-07-03 10:43
Which error are you getting? 

Thanks.

**Comment by thearabbit** [comment] 2016-09-17 01:42
Thanks for your confirm, but it don't show anything.

**Comment by joseshiru** [comment] 2016-09-26 08:47
Hi, 

Could you please give more information about the error? 
Are the CSS files getting loaded into the browser? 

I think that the Javascript file is loading properly but perhaps the CSS isn't.

One way how to test it, is checking if inside the selected element, there is one div with an id that has this pattern

>  **loader[number]**

 **after you used the ploading action "show"**.

Thanks.

**Comment by thearabbit** [comment] 2016-09-26 08:51
Don't show any error on `Inspect`.

**Comment by joseshiru** [comment] 2016-09-26 08:56
And there is a div with an id that has this pattern
`id="loader[number]"`

Inside the selected element after you used the ploading action "show" ?
For example:
![image](https://cloud.githubusercontent.com/assets/6574493/18828419/1b900eb6-83d8-11e6-87e0-1aa9468adc9d.png)

Thanks

**Comment by thearabbit** [comment] 2016-09-26 09:47
Still don't work.
This my test repo `https://github.com/thearabbit/ploading-test`

**Comment by joseshiru** [comment] 2016-09-27 09:25
Hi,

Thank you very much for create a repo. It helped me a lot 👍 

So, everything regarding the plugin is working properly.

The problem is that you're trying to show the spinner inside the div <div id="p-loading"></div> that doesn't have any CSS property as height or width, and in this case the spinner needs to be displayed inside an container that has such as properties.

So, please try to run it inside a div which has a defined enough space for the spinner.

If you want to test it, just add this to your project and you will see that it will work.

```
Template.hello.events({
  'click .show-loading'(event, instance) {
    $('html').ploading({action: 'show'});
  },
});

```

Thanks

**Comment by thearabbit** [comment] 2016-09-27 12:37
Thanks now it work fine.
but could you example me for full screen loading?

**Comment by joseshiru** [comment] 2016-09-28 08:15
Hi,

Just try to add this properties to your CSS main file:

```
html, body {
    margin: 0;
    height: 100%;
}
```

_This will make the HTML and Body fullscreen_

And then, show the spinner in the HTML:

`Template.hello.events({
  'click .show-loading'(event, instance) {
    $('html').ploading({action: 'show'});
  },
});
`

I'm closing this due to there's no issue anymore.

**Closed as completed by joseshiru** 2016-09-28 08:15 UTC

**Comment by thearabbit** [comment] 2016-09-28 11:25
Thanks again, but I would like to use with `<div id="loading"></div>`.
Could example?

**Comment by joseshiru** [comment] 2016-09-28 12:35
Hi,

Please add the CSS properties mentioned here:

http://stackoverflow.com/questions/7130397/how-do-i-make-a-div-full-screen

To your 

`<div id="loading"></div>`

**Comment by thearabbit** [comment] 2016-09-29 02:26
I tried, but can't click or use my form

``` js
// CSS
#p-loading{
    position:fixed;
    top:0;
    right:0;
    bottom:0;
    left:0;
 }
//---------- or ----------
#p-loading {
    position:absolute;
    top:0; right:0;
    bottom:0; left:0;
}
//---------

<div id="p-loading"></div>

    <form>
      <input type="textbox"><br>
      <input type="textbox"><br>
      <input type="textbox"><br>
      <input type="textbox"><br>
      <input type="textbox"><br>
    </form>

  <button class="show-loading">Show Loadin</button>
  <button class="hide-loading">Hide Loadin</button>
```

**Comment by joseshiru** [comment] 2016-09-29 08:07
Hi,

Yes, it will happen because the "p-loading" div is taking the whole screen size.

In this case you should  hide and show the div manually, as the ploading plugin is only creating a div inside the selected node (<div id="p-loading">). And also setting the _p-loading div_ as hidden by default.

So, the way how to use it will be:
//CSS

`#p-loading{
    position:absolute;
    top:0;
    right:0;
    bottom:0;
    left:0;
    display: none;
 }`

//JS
`$("#p-loading").ploading({action: 'show'}).show();`

`$("#p-loading").ploading({action: 'hide'}).hide();`

Or an easier way, just run the ploading into the body tag.

**Comment by thearabbit** [comment] 2016-09-29 08:28
Excuse me, could provide source code for your demo?
Thanks ...

![2016-09-29_15-27-23](https://cloud.githubusercontent.com/assets/4495160/18946501/5c06995a-8659-11e6-899e-b1a15e983c84.png)

**Comment by joseshiru** [comment] 2016-09-29 08:52
Hi,

Sure, please clone this repo: https://github.com/joseshiru/p-loading.git
Fetch and change to the gh-pages branch.

That branch contains the source of the website.

Steps: 

```
git clone https://github.com/joseshiru/p-loading.git

git fetch

git checkout gh-pages
```
